import { useEffect, useMemo, useState, type FormEvent } from "react";

interface Props { onLogin:(email:string,password:string)=>Promise<void>;onRegister:(email:string,password:string,displayName?:string)=>Promise<void>;onClose:()=>void; }
function messageFrom(error:unknown){return(error as{response?:{data?:{detail?:string}}})?.response?.data?.detail||"La connexion n’a pas pu être établie.";}

export default function AuthModal({onLogin,onRegister,onClose}:Props){
  const[mode,setMode]=useState<"login"|"register">("login");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[displayName,setDisplayName]=useState("");const[showPassword,setShowPassword]=useState(false);const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(false);
  const strength=useMemo(()=>[password.length>=10,/[A-Z]/.test(password)&&/[a-z]/.test(password),/\d/.test(password),/[^\w]/.test(password)].filter(Boolean).length,[password]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[onClose]);
  async function submit(event:FormEvent){event.preventDefault();setError(null);if(mode==="register"&&password!==confirm)return setError("Les mots de passe ne correspondent pas.");setLoading(true);try{if(mode==="login")await onLogin(email.trim(),password);else await onRegister(email.trim(),password,displayName.trim()||undefined);onClose();}catch(caught){setError(messageFrom(caught));}finally{setLoading(false);}}
  const field="h-12 w-full rounded-xl border border-white/[.09] bg-black/20 px-4 text-sm text-[#eef1f8] outline-none transition placeholder:text-[#657087] focus:border-[#8da9ff]/60 focus:bg-black/30 focus:shadow-[0_0_0_3px_rgba(141,169,255,.08)]";
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-[#020409]/80 p-3 backdrop-blur-xl sm:p-6" role="dialog" aria-modal="true" aria-labelledby="auth-title" onMouseDown={event=>event.target===event.currentTarget&&onClose()}>
    <div className="relative grid max-h-[94vh] w-full max-w-[920px] overflow-y-auto rounded-[28px] border border-white/10 bg-[#0b101a] shadow-[0_40px_140px_rgba(0,0,0,.75)] md:grid-cols-[.9fr_1.1fr]">
      <aside className="relative hidden min-h-[650px] overflow-hidden border-r border-white/[.07] p-9 md:flex md:flex-col md:justify-between">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_25%_22%,rgba(124,156,245,.24),transparent_32%),radial-gradient(circle_at_78%_68%,rgba(84,215,183,.13),transparent_35%),linear-gradient(155deg,#111a2b,#070a10_68%)]"/><div className="absolute left-[18%] top-[25%] h-2 w-2 rounded-full bg-[#8da9ff] shadow-[0_0_30px_8px_rgba(141,169,255,.55)]"/><div className="absolute right-[20%] top-[42%] h-1.5 w-1.5 rounded-full bg-[#54d7b7] shadow-[0_0_24px_6px_rgba(84,215,183,.35)]"/><div className="absolute bottom-[30%] left-[35%] h-1 w-1 rounded-full bg-white shadow-[0_0_20px_5px_rgba(255,255,255,.3)]"/><svg className="absolute inset-0 h-full w-full opacity-30" viewBox="0 0 400 650" aria-hidden="true"><path d="M72 162 C145 205 246 195 312 276 S225 420 144 455" fill="none" stroke="url(#authLine)" strokeWidth="1"/><path d="M88 510 C160 390 250 370 330 194" fill="none" stroke="url(#authLine)" strokeWidth=".7"/><defs><linearGradient id="authLine"><stop stopColor="#8da9ff"/><stop offset="1" stopColor="#54d7b7" stopOpacity=".1"/></linearGradient></defs></svg>
        <div className="relative"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eef1f8] font-display text-2xl text-[#080c13]">A</div><p className="mt-4 font-mono text-[9px] uppercase tracking-[.28em] text-[#8da9ff]">Espace personnel</p></div>
        <div className="relative"><blockquote className="font-display text-[31px] leading-[1.12] text-[#f2efe7]">Gardez une trace des idées qui vous déplacent.</blockquote><p className="mt-5 max-w-xs text-sm leading-6 text-[#99a3b7]">Vos favoris, vos parcours et vos futures collections restent liés à votre espace Atlas.</p><div className="mt-8 flex gap-5 border-t border-white/10 pt-5 text-[10px] text-[#778197]"><span>Cookie protégé</span><span>Données privées</span><span>Session 7 jours</span></div></div>
      </aside>
      <section className="relative p-6 sm:p-10 md:p-12"><button type="button" onClick={onClose} aria-label="Fermer" className="absolute right-5 top-5 grid h-9 w-9 place-items-center rounded-full border border-white/10 text-lg text-ink-dim hover:bg-white/5 hover:text-white">×</button>
        <div className="pr-10"><p className="font-mono text-[9px] uppercase tracking-[.25em] text-[#8da9ff]">{mode==="login"?"Heureux de vous revoir":"Créer votre espace"}</p><h2 id="auth-title" className="mt-3 font-display text-4xl leading-tight text-[#f2efe7]">{mode==="login"?"Reprendre l’exploration":"Composer votre Atlas"}</h2><p className="mt-3 text-sm leading-6 text-[#8f99ad]">{mode==="login"?"Retrouvez vos repères exactement là où vous les aviez laissés.":"Enregistrez vos découvertes et construisez une bibliothèque personnelle."}</p></div>
        <div className="my-7 grid grid-cols-2 border-b border-white/10"><button type="button" onClick={()=>{setMode("login");setError(null);}} className={`border-b-2 py-3 text-sm transition ${mode==="login"?"border-[#8da9ff] text-white":"border-transparent text-ink-dim hover:text-white"}`}>Connexion</button><button type="button" onClick={()=>{setMode("register");setError(null);}} className={`border-b-2 py-3 text-sm transition ${mode==="register"?"border-[#8da9ff] text-white":"border-transparent text-ink-dim hover:text-white"}`}>Créer un compte</button></div>
        <form onSubmit={submit} className="space-y-4">
          {mode==="register"&&<label className="block"><span className="mb-2 block text-[11px] text-[#aab2c2]">Nom affiché <em className="font-normal text-ink-dim">— facultatif</em></span><input value={displayName} maxLength={64} onChange={e=>setDisplayName(e.target.value)} placeholder="Ada, Emmy, Alexandre…" className={field}/></label>}
          <label className="block"><span className="mb-2 block text-[11px] text-[#aab2c2]">Adresse e-mail</span><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="vous@exemple.fr" className={field}/></label>
          <label className="block"><span className="mb-2 block text-[11px] text-[#aab2c2]">Mot de passe</span><span className="relative block"><input type={showPassword?"text":"password"} autoComplete={mode==="login"?"current-password":"new-password"} required minLength={mode==="register"?10:undefined} maxLength={72} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==="login"?"Votre mot de passe":"10 caractères minimum"} className={`${field} pr-24`}/><button type="button" onClick={()=>setShowPassword(value=>!value)} className="absolute right-4 top-1/2 -translate-y-1/2 text-[11px] text-[#8da9ff] hover:text-white">{showPassword?"Masquer":"Afficher"}</button></span></label>
          {mode==="register"&&<><div className="flex gap-1" aria-label={`Robustesse ${strength} sur 4`}>{[1,2,3,4].map(level=><span key={level} className={`h-1 flex-1 rounded-full ${strength>=level?(strength<3?"bg-[#f5a97f]":"bg-[#54d7b7]"):"bg-white/10"}`}/>)}</div><label className="block"><span className="mb-2 block text-[11px] text-[#aab2c2]">Confirmer le mot de passe</span><input type={showPassword?"text":"password"} required minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Saisissez-le une seconde fois" className={field}/></label></>}
          {error&&<p role="alert" className="rounded-xl border border-[#f07178]/20 bg-[#f07178]/[.07] px-4 py-3 text-xs leading-5 text-[#ff9b9f]">{error}</p>}
          <button disabled={loading} className="group mt-2 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#eef1f8] text-sm font-semibold text-[#080c13] transition hover:bg-white disabled:cursor-wait disabled:opacity-60"><span>{loading?"Vérification…":mode==="login"?"Entrer dans Atlas":"Créer mon espace"}</span><span className="transition-transform group-hover:translate-x-1">→</span></button>
          <p className="pt-1 text-center text-[10px] leading-4 text-[#667187]">Authentification sécurisée par cookie HTTP-only. Aucun mot de passe n’est conservé dans le navigateur.</p>
        </form>
      </section>
    </div>
  </div>;
}
