import type { GraphNode } from "../types";

interface Props { open: boolean; onClose: () => void; favorites: GraphNode[]; recent: GraphNode[]; signedIn: boolean; onSelect: (id: string) => void; onRemove: (id: string) => void; onLogin: () => void; }
export default function LibraryPanel({ open,onClose,favorites,recent,signedIn,onSelect,onRemove,onLogin }: Props) {
  if (!open) return null;
  const List = ({items,favorite=false}:{items:GraphNode[];favorite?:boolean}) => <div className="space-y-1.5">{items.map((n) => <div key={n.id} className="group flex items-center rounded-xl border border-transparent bg-white/[.025] hover:border-white/10"><button onClick={() => onSelect(n.id)} className="min-w-0 flex-1 px-3 py-2.5 text-left"><span className="block truncate text-sm">{n.label}</span><span className="text-[10px] text-ink-dim">{n.degree} connexions</span></button>{favorite && <button onClick={() => onRemove(n.id)} aria-label={`Retirer ${n.label} des favoris`} className="mr-2 rounded-lg p-2 text-[#ffd166] opacity-70 hover:bg-white/5">★</button>}</div>)}</div>;
  return <div className="fixed inset-0 z-40 bg-black/45 backdrop-blur-sm" onMouseDown={onClose}><aside onMouseDown={(e) => e.stopPropagation()} className="ml-auto h-full w-full max-w-md overflow-y-auto border-l border-white/10 bg-[#0d1421]/96 p-6 shadow-2xl"><div className="flex justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.2em] text-[#ffd166]">Ma bibliothèque</p><h2 className="mt-1 font-display text-3xl">Vos repères</h2></div><button onClick={onClose} aria-label="Fermer la bibliothèque" className="text-2xl text-ink-dim">×</button></div>
    <section className="mt-8"><div className="mb-3 flex items-end justify-between"><h3 className="text-sm font-semibold">Favoris</h3><span className="text-[10px] text-ink-dim">{favorites.length}</span></div>{!signedIn ? <button onClick={onLogin} className="w-full rounded-xl border border-white/10 p-4 text-left text-xs text-ink-dim hover:bg-white/5">Connectez-vous pour synchroniser vos repères sur tous vos appareils →</button> : favorites.length ? <List items={favorites} favorite /> : <p className="rounded-xl border border-dashed border-white/10 p-4 text-xs leading-5 text-ink-dim">Ajoutez une étoile depuis une fiche : vos points de repère apparaîtront ici et brilleront en or dans le graphe.</p>}</section>
    <section className="mt-8"><div className="mb-3 flex items-end justify-between"><h3 className="text-sm font-semibold">Récemment explorés</h3><span className="text-[10px] text-ink-dim">{recent.length}</span></div>{recent.length ? <List items={recent} /> : <p className="text-xs text-ink-dim">Votre chemin se dessinera au fil de la navigation.</p>}</section>
  </aside></div>;
}
