import { startTransition, useDeferredValue, useMemo, useState } from "react";
import type { GraphData, GraphNode } from "../types";

interface Props { graph: GraphData | null; onSelectNode: (id: string) => void; onLensChange: (ids: Set<string>, label: string) => void; }
const MAX_RESULTS=60;
const norm=(text:string)=>text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

export default function SearchBar({graph,onSelectNode,onLensChange}:Props){
  const[query,setQuery]=useState("");const[open,setOpen]=useState(false);const[cursor,setCursor]=useState(0);const deferredQuery=useDeferredValue(query);
  const index=useMemo(()=>graph?.nodes.map(node=>({node,label:norm(node.label),description:norm(node.description||"")}))||[],[graph]);
  const adjacency=useMemo(()=>{const map=new Map<string,Set<string>>();graph?.edges.forEach(edge=>{if(!map.has(edge.source))map.set(edge.source,new Set());if(!map.has(edge.target))map.set(edge.target,new Set());map.get(edge.source)!.add(edge.target);map.get(edge.target)!.add(edge.source);});return map;},[graph]);
  const results=useMemo(()=>{const q=norm(deferredQuery.trim());if(!q)return[];return index.map(({node,label,description})=>{const matchScore=label===q?1200:label.startsWith(q)?850:label.includes(q)?560:description.includes(q)?220:0;return{node,matchScore,score:matchScore+Math.min(160,node.degree*4)};}).filter(item=>item.matchScore>0).sort((a,b)=>b.score-a.score).slice(0,MAX_RESULTS).map(item=>item.node);},[deferredQuery,index]);
  function update(value:string){setQuery(value);setOpen(true);setCursor(0);const q=norm(value.trim());startTransition(()=>{if(!q)return onLensChange(new Set(),"");const matches=index.filter(item=>item.label.includes(q)||item.description.includes(q)).map(item=>item.node.id);const context=new Set(matches);matches.forEach(id=>adjacency.get(id)?.forEach(neighbor=>context.add(neighbor)));onLensChange(context,`Recherche : ${value.trim()}`);});}
  function select(node:GraphNode){onSelectNode(node.id);setQuery("");setOpen(false);onLensChange(new Set(),"");}
  return <div className="relative mx-auto w-full max-w-2xl">
    <div className="group flex items-center rounded-2xl border border-white/10 bg-[#111827]/75 px-4 shadow-[0_16px_60px_rgba(0,0,0,.3)] backdrop-blur-xl focus-within:border-white/25"><span className="mr-3 text-category-algorithm">⌕</span><input id="atlas-search" value={query} onChange={e=>update(e.target.value)} onFocus={()=>setOpen(true)} onBlur={()=>window.setTimeout(()=>setOpen(false),160)} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setCursor(c=>Math.min(results.length-1,c+1));}if(e.key==="ArrowUp"){e.preventDefault();setCursor(c=>Math.max(0,c-1));}if(e.key==="Enter"&&results[cursor])select(results[cursor]);if(e.key==="Escape"){update("");setOpen(false);}}} placeholder="Chercher une idée, une personne, une phrase…" className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-ink-dim"/><kbd className="hidden rounded-md border border-white/10 px-1.5 py-0.5 font-mono text-[9px] text-ink-dim sm:block">/</kbd></div>
    {open&&query.trim()&&<div className="absolute left-0 right-0 top-14 z-50 overflow-hidden rounded-2xl border border-white/10 bg-[#111827]/95 shadow-2xl backdrop-blur-2xl"><div className="flex items-center justify-between border-b border-white/[.06] px-4 py-3"><span className="font-mono text-[9px] uppercase tracking-[.18em] text-ink-dim">Résultats dans tout l’Atlas</span><span className="text-[10px] text-ink-dim">{results.length}{results.length===MAX_RESULTS?"+":""} correspondances</span></div><div className="max-h-[min(68vh,560px)] overflow-y-auto p-2">
      {results.map((node,indexResult)=><button key={node.id} onMouseDown={e=>e.preventDefault()} onClick={()=>select(node)} onMouseEnter={()=>setCursor(indexResult)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left ${cursor===indexResult?"bg-white/[.08]":"hover:bg-white/[.05]"}`}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-white/10 bg-white/[.03] text-[10px] text-ink-dim">{node.degree}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm text-ink">{node.label}</span><span className="mt-0.5 block truncate text-[11px] text-ink-dim">{node.description||`${node.degree} connexions`}</span></span><span className="text-xs text-ink-dim">↵</span></button>)}
      {!results.length&&<p className="px-3 py-8 text-center text-xs text-ink-dim">Aucune correspondance fiable dans la base actuelle.</p>}
    </div></div>}
  </div>;
}
